### ISSUE TITLE
Not working the default Rollup Config of Sapper instead of Webpack

### ISSUE THREAD

**Issue by ktryndchrs** [kaisermann/sapper-template-i18n#3]
Both Client & Server sides error indicates this:
`Unexpected token (Note that you need @rollup/plugin-json to import JSON files)`

With the following error
```
Error: Cannot find module '/Users/catherine/Sites/project/__sapper__/dev/server/server.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1029:15)
    at Function.Module._load (internal/modules/cjs/loader.js:898:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

I will try to sort it and if I find the solution, I'l post it here

**Comment by ktryndchrs** [comment]
Installing 
@rollup/plugin-json then importing it in rollup.config does the trick


```
(...)
import json from '@rollup/plugin-json';
(...)

export default {
	client: {
		(...)
		plugins: [
			 json(),
			svelte({
				dev,
				hydratable: true,
				emitCss: true
			}),
			(...)
		],

	(...)

	server: {
		(...)
		plugins: [
			(...)
			json(),
			svelte({
				generate: 'ssr',
				dev
			}),
			(...)
		],
(...)
```
